# Generated by Django 4.0.3 on 2022-04-10 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alternatepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlternatePage',
        ),
    ]
